name: Run Python Script on CSV/Feature Changes

on:
  push:
    paths:
      - '**/*.csv'
      - '**/*.feature'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # adjust version as needed

      # Step 3: Install dependencies (adjust if you have requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run your Python script
      - name: Run script
        run: |
          cd Artifacts
          ImportPipelineController.py
